title: Rebekah Adams and Jack Rummler # your name (or website title) here
logo: "/images/flex_logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MUSA 508 
  <br><br>
  Final Project
  <br><br>
  <a href="https://www.youtube.com/watch?v=vrF7Rini-4M">Watch our presentation on You Tube</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
